package com.sandeepreddy.tournament.db;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id(autoincrement = true)
    private Long id;


    @Unique
    @NotNull
    private String fbId;

    @NotNull
    private String name;
    private String imageUrl;
    private Boolean pinned;
    private String color;

    @Generated(hash = 1830943993)
    public User(Long id, @NotNull String fbId, @NotNull String name,
            String imageUrl, Boolean pinned, String color) {
        this.id = id;
        this.fbId = fbId;
        this.name = name;
        this.imageUrl = imageUrl;
        this.pinned = pinned;
        this.color = color;
    }
    @Generated(hash = 586692638)
    public User() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getFbId() {
        return this.fbId;
    }
    public void setFbId(String fbId) {
        this.fbId = fbId;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Boolean getPinned() {
        return this.pinned;
    }
    public void setPinned(Boolean pinned) {
        this.pinned = pinned;
    }
    public String getColor() {
        return this.color;
    }
    public void setColor(String color) {
        this.color = color;
    }
    
}
